image:
  tag: "latest"
app:
  port: 1337

service:
  type: ClusterIP
  port: 1337

replicaCount: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: yopass.radioco.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 128m
    memory: 256Mi
  requests:
    cpu: 32m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80